### ISSUE TITLE
Airgun support for Satellite entities and views

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/airgun#120]
(Work in progress, will submit issue per each entity and check off completed ones)

### Entities with t2/t3 tests available, required for GA:
* [x] Dashboard https://github.com/SatelliteQE/airgun/issues/147
* [x] Red Hat Subscriptions #130
* [x] Products #58 
* [x] Bookmarks #151
* [x] Repositories #99
* [x] Content Credentials #128
* [x] Sync Plans #127 
* [x] Sync Status #131 
* [x] Lifecycle Environments #123
* [x] Content Views #122
* [x] Activation Keys #121
* [x] Container Image Tags (Docker Tags) #132
* [x] Errata #133 
* [x] Packages #137 
* [x] Containers #149 
* [x] Hosts #138
* [x] Discovered Hosts #150
* [x] Content Hosts #141 
* [x] Host Collections https://github.com/SatelliteQE/airgun/issues/136
* [x] Partition Tables https://github.com/SatelliteQE/airgun/issues/78
* [x] Operating Systems https://github.com/SatelliteQE/airgun/issues/139
* [x] Provisioning Templates https://github.com/SatelliteQE/airgun/issues/140
* [x] Compliance Policies https://github.com/SatelliteQE/airgun/issues/144
* [x] SCAP Contents https://github.com/SatelliteQE/airgun/issues/143
* [x] Tailoring Files https://github.com/SatelliteQE/airgun/issues/142
* [x] Discovery Rules #118
* [x] Puppet Environments https://github.com/SatelliteQE/airgun/issues/106
* [x] Smart Variables https://github.com/SatelliteQE/airgun/issues/25
* [x] Smart Class Parameters https://github.com/SatelliteQE/airgun/issues/135
* [x] Subnets https://github.com/SatelliteQE/airgun/issues/126
* [x] Domains https://github.com/SatelliteQE/airgun/issues/75
* [x] Locations https://github.com/SatelliteQE/airgun/issues/134
* [x] Organizations https://github.com/SatelliteQE/airgun/issues/77
* [x] LDAP Authentication https://github.com/SatelliteQE/airgun/issues/129
* [x] Users https://github.com/SatelliteQE/airgun/issues/124
* [x] User Groups https://github.com/SatelliteQE/airgun/issues/88
* [x] Roles https://github.com/SatelliteQE/airgun/issues/91
* [x] Job Templates https://github.com/SatelliteQE/airgun/issues/145
* [x] Job Invocations https://github.com/SatelliteQE/airgun/issues/146
* [x] Puppet Classes https://github.com/SatelliteQE/airgun/issues/153

### Entities with no t2/t3 tests, not required for GA:
* [ ] Facts
* [ ] Statistics
* [x] Trends
* [x] Audit
* [ ] Jobs
* [ ] Tasks
* [ ] Config Reports
* [ ] Recurring Logics
* [ ] Red Hat Repositories
* [ ] Files
* [ ] OSTree Branches
* [ ] Puppet Modules
* [ ] Registries
* [x] Architectures
* [ ] Hardware Models
* [ ] Media
* [ ] Compliance Reports
* [ ] Host Groups
* [ ] Global Parameters
* [ ] Config Groups
* [ ] Ansible Roles
* [ ] Capsules
* [ ] Virt who configs
* [ ] Compute Profiles
* [ ] HTTP Capsules
* [ ] Realms
* [ ] Settings
* [ ] Access Insights

**Comment by mirzal** [comment]
All entities required for GA are implemented and we already sent public message that Airgun framework is ready.

Obviously there are still entities or widgets in Satellite that are not implemented in Airgun, but we can work on them when need arises.
