### ISSUE TITLE
6.7.z branch

### ISSUE THREAD

**Issue by mirekdlugosz** [SatelliteQE/airgun#478]
Issue for tracking 6.7.z branching in Nailgun. Once all items on list below are Done, we can branch off.
- [x] #198 - old POC, not a branching blocker
- [x] #329 - stalled, not a branching blocker
- [x] #368 - labeled DO NOT MERGE, not a branching blocker
- [x] #419 - labeled DO NOT MERGE, not a branching blocker
- [x] #471 - labeled DO NOT MERGE, not a branching blocker
- [x] #477 - merged

**Comment by mirekdlugosz** [comment]
Branch created out of 9693ae817dd1ae328ece75f2eedb6975aa096c67
